"""File Generated by Sideko (sideko.dev)"""

from sms_messaging_interface.core import AsyncBaseClient, SyncBaseClient
from sms_messaging_interface.resources.x.smsmessaging import (
    SmsmessagingClient,
    AsyncSmsmessagingClient,
)


class XClient:
    def __init__(self, *, base_client: SyncBaseClient):
        self._base_client = base_client
        # register sync resources (keep comment for code generation)
        self.smsmessaging = SmsmessagingClient(base_client=self._base_client)

    # register sync api methods (keep comment for code generation)


class AsyncXClient:
    def __init__(self, *, base_client: AsyncBaseClient):
        self._base_client = base_client
        # register async resources (keep comment for code generation)
        self.smsmessaging = AsyncSmsmessagingClient(base_client=self._base_client)

    # register async api methods (keep comment for code generation)
