"""File Generated by Sideko (sideko.dev)"""

from sms_messaging_interface.core import AsyncBaseClient, SyncBaseClient
from sms_messaging_interface.resources.smsmessaging.v1.inbound import (
    AsyncInboundClient,
    InboundClient,
)
from sms_messaging_interface.resources.smsmessaging.v1.outbound import (
    OutboundClient,
    AsyncOutboundClient,
)


class V1Client:
    def __init__(self, *, base_client: SyncBaseClient):
        self._base_client = base_client
        # register sync resources (keep comment for code generation)
        self.inbound = InboundClient(base_client=self._base_client)
        self.outbound = OutboundClient(base_client=self._base_client)

    # register sync api methods (keep comment for code generation)


class AsyncV1Client:
    def __init__(self, *, base_client: AsyncBaseClient):
        self._base_client = base_client
        # register async resources (keep comment for code generation)
        self.inbound = AsyncInboundClient(base_client=self._base_client)
        self.outbound = AsyncOutboundClient(base_client=self._base_client)

    # register async api methods (keep comment for code generation)
