"""File Generated by Sideko (sideko.dev)"""

import pytest
from open_gateway_onboarding_and_ordering_api import AsyncClient, Client
from os import getenv
from pydantic import TypeAdapter

# test sync & async methods (keep comment for code generation)


def test_list_200_generated_success():
    """Test description"""
    # tests calling sync method with example data (keep comment for code generation)
    client = Client(oauth_token=getenv("API_TOKEN"))
    response = client.status.list()
    adapter = TypeAdapter(None)
    adapter.validate_python(response)


@pytest.mark.asyncio
async def test_await_list_200_generated_success():
    """Test description"""
    # tests calling async method with example data (keep comment for code generation)
    client = AsyncClient(oauth_token=getenv("API_TOKEN"))
    response = await client.status.list()
    adapter = TypeAdapter(None)
    adapter.validate_python(response)
