"""File Generated by Sideko (sideko.dev)"""

from sms_messaging_interface import Client, AsyncClient


def test_init_client():
    """Tests initializing sdk client with all authentication methods"""
    Client()


def test_init_async_client():
    """Tests initializing async sdk client with all authentication methods"""
    AsyncClient()


# test sync & async methods (keep comment for code generation)
