"""File Generated by Sideko (sideko.dev)"""

from open_gateway_onboarding_and_ordering_api import Client, AsyncClient
from os import getenv


def test_init_client():
    """Tests initializing sdk client with all authentication methods"""
    Client(oauth_token=getenv("API_TOKEN"))


def test_init_async_client():
    """Tests initializing async sdk client with all authentication methods"""
    AsyncClient(oauth_token=getenv("API_TOKEN"))


# test sync & async methods (keep comment for code generation)
