"""File Generated by Sideko (sideko.dev)"""

import io
import typing

from pydantic import (
    BaseModel as _PydanticBaseModel,
    Field as _PydanticField,
    ConfigDict as _PydanticConfigDict,
)

ModelFiles = typing.List[
    typing.Tuple[str, typing.Union[typing.BinaryIO, io.BufferedReader]]
]


class InboundSmsMessage(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    date_time: typing.Optional[str] = _PydanticField(alias="dateTime", default=None)
    destination_address: typing.Optional[str] = _PydanticField(
        alias="destinationAddress", default=None
    )
    message: typing.Optional[str] = _PydanticField(alias="message", default=None)
    message_id: typing.Optional[str] = _PydanticField(alias="messageId", default=None)
    resource_url: typing.Optional[str] = _PydanticField(
        alias="resourceURL", default=None
    )
    sender_address: typing.Optional[str] = _PydanticField(
        alias="senderAddress", default=None
    )


class InboundSmsMessageListRsp(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    inbound_sms_message: typing.Optional[typing.List[InboundSmsMessage]] = (
        _PydanticField(alias="inboundSMSMessage", default=None)
    )
    number_of_messages_in_this_batch: typing.Optional[str] = _PydanticField(
        alias="numberOfMessagesInThisBatch", default=None
    )
    resource_url: typing.Optional[str] = _PydanticField(
        alias="resourceURL", default=None
    )
    total_number_of_pending_messages: typing.Optional[str] = _PydanticField(
        alias="totalNumberOfPendingMessages", default=None
    )


class InboundSmsMessageListRspCall(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    inbound_sms_message_list: typing.Optional[InboundSmsMessageListRsp] = (
        _PydanticField(alias="inboundSMSMessageList", default=None)
    )
