"""File Generated by Sideko (sideko.dev)"""

import pytest
from sms_messaging_interface import AsyncClient, Client
from sms_messaging_interface.types.smsmessaging.v1.outbound.requests.delivery_infos import (
    models,
)
from pydantic import TypeAdapter

# test sync & async methods (keep comment for code generation)


def test_list_200_generated_success():
    """Test description"""
    # tests calling sync method with example data (keep comment for code generation)
    client = Client()
    response = client.smsmessaging.v1.outbound.requests.delivery_infos.list(
        sender_address="string", request_id="string"
    )
    adapter = TypeAdapter(models.DeliveryInfoListRspCall)
    adapter.validate_python(response)


@pytest.mark.asyncio
async def test_await_list_200_generated_success():
    """Test description"""
    # tests calling async method with example data (keep comment for code generation)
    client = AsyncClient()
    response = await client.smsmessaging.v1.outbound.requests.delivery_infos.list(
        sender_address="string", request_id="string"
    )
    adapter = TypeAdapter(models.DeliveryInfoListRspCall)
    adapter.validate_python(response)
