"""File Generated by Sideko (sideko.dev)"""

import pytest
from open_gateway_onboarding_and_ordering_api import AsyncClient, Client
from os import getenv
import typing
from pydantic import TypeAdapter

# test sync & async methods (keep comment for code generation)


def test_get_200_generated_success():
    """Test description"""
    # tests calling sync method with example data (keep comment for code generation)
    client = Client(oauth_token=getenv("API_TOKEN"))
    response = client.api_product.get(id="string", fields="string")
    adapter = TypeAdapter(typing.Any)
    adapter.validate_python(response)


@pytest.mark.asyncio
async def test_await_get_200_generated_success():
    """Test description"""
    # tests calling async method with example data (keep comment for code generation)
    client = AsyncClient(oauth_token=getenv("API_TOKEN"))
    response = await client.api_product.get(id="string", fields="string")
    adapter = TypeAdapter(typing.Any)
    adapter.validate_python(response)


def test_list_200_generated_success():
    """Test description"""
    # tests calling sync method with example data (keep comment for code generation)
    client = Client(oauth_token=getenv("API_TOKEN"))
    response = client.api_product.list(fields="string", limit=123, offset=123)
    adapter = TypeAdapter(typing.List[typing.Any])
    adapter.validate_python(response)


@pytest.mark.asyncio
async def test_await_list_200_generated_success():
    """Test description"""
    # tests calling async method with example data (keep comment for code generation)
    client = AsyncClient(oauth_token=getenv("API_TOKEN"))
    response = await client.api_product.list(fields="string", limit=123, offset=123)
    adapter = TypeAdapter(typing.List[typing.Any])
    adapter.validate_python(response)
