"""File Generated by Sideko (sideko.dev)"""

import io
import typing

from pydantic import (
    BaseModel as _PydanticBaseModel,
    Field as _PydanticField,
    ConfigDict as _PydanticConfigDict,
)

ModelFiles = typing.List[
    typing.Tuple[str, typing.Union[typing.BinaryIO, io.BufferedReader]]
]


class DeliveryInfo(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    address: typing.Optional[str] = _PydanticField(alias="address", default=None)
    delivery_status: typing.Optional[str] = _PydanticField(
        alias="deliveryStatus", default=None
    )


class OutboundSmsTextMessage(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    message: typing.Optional[str] = _PydanticField(alias="message", default=None)


class CallbackReference(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    callback_data: typing.Optional[str] = _PydanticField(
        alias="callbackData", default=None
    )
    notify_url: typing.Optional[str] = _PydanticField(alias="notifyURL", default=None)


class DeliveryInfoListRsp(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    delivery_info: typing.Optional[typing.List[DeliveryInfo]] = _PydanticField(
        alias="deliveryInfo", default=None
    )
    resource_url: typing.Optional[str] = _PydanticField(
        alias="resourceURL", default=None
    )


class OutboundSmsMessageRsp(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    address: typing.Optional[typing.List[str]] = _PydanticField(
        alias="address", default=None
    )
    client_correlator: typing.Optional[str] = _PydanticField(
        alias="clientCorrelator", default=None
    )
    delivery_info_list: typing.Optional[DeliveryInfoListRsp] = _PydanticField(
        alias="deliveryInfoList", default=None
    )
    outbound_sms_text_message: typing.Optional[OutboundSmsTextMessage] = _PydanticField(
        alias="outboundSMSTextMessage", default=None
    )
    receipt_request: typing.Optional[CallbackReference] = _PydanticField(
        alias="receiptRequest", default=None
    )
    resource_url: typing.Optional[str] = _PydanticField(
        alias="resourceURL", default=None
    )
    sender_address: typing.Optional[str] = _PydanticField(
        alias="senderAddress", default=None
    )
    sender_name: typing.Optional[str] = _PydanticField(alias="senderName", default=None)


class OutboundSmsMessageRspCall(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    outbound_sms_message_request: typing.Optional[OutboundSmsMessageRsp] = (
        _PydanticField(alias="outboundSMSMessageRequest", default=None)
    )
