"""File Generated by Sideko (sideko.dev)"""

import enum


class Environment(enum.Enum):
    DEFAULT = "https://api-sandbox.vf-dmp.engineering.vodafone.com/tmf-api/openGatewayOperateAPIOnboardingAndOrdering/v5"
