"""File Generated by Sideko (sideko.dev)"""

from sms_messaging_interface.core import SyncBaseClient, AsyncBaseClient
from sms_messaging_interface.resources.x.smsmessaging.v1.inbound.registrations.messages import (
    AsyncMessagesClient,
    MessagesClient,
)


class RegistrationsClient:
    def __init__(self, *, base_client: SyncBaseClient):
        self._base_client = base_client
        # register sync resources (keep comment for code generation)
        self.messages = MessagesClient(base_client=self._base_client)

    # register sync api methods (keep comment for code generation)


class AsyncRegistrationsClient:
    def __init__(self, *, base_client: AsyncBaseClient):
        self._base_client = base_client
        # register async resources (keep comment for code generation)
        self.messages = AsyncMessagesClient(base_client=self._base_client)

    # register async api methods (keep comment for code generation)
