"""File Generated by Sideko (sideko.dev)"""

import enum


class Environment(enum.Enum):
    DEFAULT = "https://api-sandbox.vf-dmp.engineering.vodafone.com/omn/api/"
    SERVER_1 = "https://api.vf-dmp.engineering.vodafone.com/omn/api/"
