"""File Generated by Sideko (sideko.dev)"""

import pytest
from sms_messaging_interface import AsyncClient, Client
from pydantic import TypeAdapter
from sms_messaging_interface.types.smsmessaging.v1.outbound.subscriptions import models

# test sync & async methods (keep comment for code generation)


def test_create_201_generated_success_default():
    """Test description"""
    # tests calling sync method with example data (keep comment for code generation)
    client = Client()
    response = client.smsmessaging.v1.outbound.subscriptions.create(
        sender_address="string",
        data={
            "delivery_receipt_subscription": {
                "callback_reference": {
                    "callback_data": "some data useful to the requestor",
                    "notify_url": "http://application-url/notify",
                },
                "filter_criteria": "string",
            }
        },
    )
    adapter = TypeAdapter(models.DeliverySubscriptionRspCall)
    adapter.validate_python(response)


@pytest.mark.asyncio
async def test_await_create_201_generated_success_default():
    """Test description"""
    # tests calling async method with example data (keep comment for code generation)
    client = AsyncClient()
    response = await client.smsmessaging.v1.outbound.subscriptions.create(
        sender_address="string",
        data={
            "delivery_receipt_subscription": {
                "callback_reference": {
                    "callback_data": "some data useful to the requestor",
                    "notify_url": "http://application-url/notify",
                },
                "filter_criteria": "string",
            }
        },
    )
    adapter = TypeAdapter(models.DeliverySubscriptionRspCall)
    adapter.validate_python(response)


def test_delete_204_generated_success():
    """Test description"""
    # tests calling sync method with example data (keep comment for code generation)
    client = Client()
    response = client.smsmessaging.v1.outbound.subscriptions.delete(
        sender_address="string", subscription_id="string"
    )
    adapter = TypeAdapter(None)
    adapter.validate_python(response)


@pytest.mark.asyncio
async def test_await_delete_204_generated_success():
    """Test description"""
    # tests calling async method with example data (keep comment for code generation)
    client = AsyncClient()
    response = await client.smsmessaging.v1.outbound.subscriptions.delete(
        sender_address="string", subscription_id="string"
    )
    adapter = TypeAdapter(None)
    adapter.validate_python(response)
