"""File Generated by Sideko (sideko.dev)"""

from sms_messaging_interface.core import SyncBaseClient, AsyncBaseClient
from sms_messaging_interface.resources.x.smsmessaging.v1.outbound.subscriptions import (
    AsyncSubscriptionsClient,
    SubscriptionsClient,
)
from sms_messaging_interface.resources.x.smsmessaging.v1.outbound.requests import (
    AsyncRequestsClient,
    RequestsClient,
)


class OutboundClient:
    def __init__(self, *, base_client: SyncBaseClient):
        self._base_client = base_client
        # register sync resources (keep comment for code generation)
        self.subscriptions = SubscriptionsClient(base_client=self._base_client)
        self.requests = RequestsClient(base_client=self._base_client)

    # register sync api methods (keep comment for code generation)


class AsyncOutboundClient:
    def __init__(self, *, base_client: AsyncBaseClient):
        self._base_client = base_client
        # register async resources (keep comment for code generation)
        self.subscriptions = AsyncSubscriptionsClient(base_client=self._base_client)
        self.requests = AsyncRequestsClient(base_client=self._base_client)

    # register async api methods (keep comment for code generation)
